### ISSUE TITLE
Addon title and description strings do not match specifications

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mikedeboer/shield-search-nudges#11]
[Affected versions]:
- Nightly Version 63.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.shield-search-nudges.variation" boolean pref is set to "doshow".
- Doorhanger Nudges version 1.4.0 addon is installed.

[Steps to reproduce]:
1. Open the browser and navigate to the about:addons page.
2. Observe the Addon's title and description.

[Expected result]:
- "User search study" title is displayed.
- "This is a study to understand how users interact with search engines in Firefox." description is displayed.

[Actual result]:
- "Showing a search doorhanger when the urlbar is focused study." title is displayed.
- "Study to measure if showing a doorhanger to introduce search using the urlbar is helpful" description is displayed.

[Notes]:
- I have attached a screenshot of the issue:
![title and description](https://user-images.githubusercontent.com/40393891/43896042-18208c0c-9be0-11e8-8ff8-83b439cfd399.png)

**Comment by Standard8** [comment]
@Softvision-PatriciuPop Where are the specifications for this? I'll gladly change it, mainly curious though as I don't remember seeing anything about it.

**Comment by Softvision-PatriciuPop** [comment]
You can find these details on the final page of the PHD, the User facing title of the experiment and User facing description of the experiment:
https://docs.google.com/document/d/1-F8toIUWo99fl1iFsnTen262C-8N1TbEHPot6sqh9FA/edit#

**Comment by Standard8** [comment]
Thank you, I had missed that.

**Comment by Softvision-PatriciuPop** [comment]
I've verified this issue and it's no longer reproducible using the latest version of Search Nudges addon (1.5.1). Tested on Windows 10 x64, Mac 10.13.6 and Arch Linux 4.12.
