### ISSUE TITLE
The experiment wrongly remains installed after the study expires

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mikedeboer/shield-search-nudges#14]
[Affected versions]:
- Firefox 61.0.2 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
"extensions.legacy.enabled" set to true;
create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Change the date from the system, into future (at least 6 weeks).
3. Restart the browser.
4. Navigate to the "about:addons" page -> Extensions tab and observe the installed addons.
  
[Expected result]:
- The "Search Nudges" add-on is no longer installed.

[Actual result]:
- The "Search Nudges" add-on is still installed.

[Notes]:
- Based on the [PHD document](https://docs.google.com/document/d/1-F8toIUWo99fl1iFsnTen262C-8N1TbEHPot6sqh9FA/edit#), the duration of the experiment is 6 weeks.
- Here is a screen recording with this issue: https://goo.gl/CYijjR

**Comment by Softvision-CristinaBadescu** [comment]
I've tested this issue and it is still reproducible using the latest version of "Search Nudges" add-on (1.5.1), on Windows 10 x64, Mac 10.13.6 and Ubuntu 16.04.
Considering this, the issue should be reopened (I don't have the right to do this, at the moment).

**Comment by mikedeboer** [comment]
I don't think this is the correct way to test this, because we'll be distributing this addon through Normandy, which takes care of its lifetime. In other words: Normandy will disable the addon once it's set to expire - not using the system clock.
Am I right?

**Comment by Softvision-CristinaBadescu** [comment]
The main pain point, in this case, is the possibility of Normandy failing and because we have no control over this it would be better for us to implement an expiry based on the install time and have Normandy be a backup plan.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest "Search Nudges" version (1.6.0) and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
