### ISSUE TITLE
"Doorhanger Nudges" shield study is not removed when the "Disable" button from "about:addons" page is clicked 

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mikedeboer/shield-search-nudges#15]
Affected versions]:
- Firefox release Version 61.0.2
- Nightly Version 63.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.shield-search-nudges.variation" boolean pref is set to "doshow".
- Doorhanger Nudges version 1.4.0 addon is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons>Extensions" and click the "Doorhanger Nudges" add-on.
3. Click the "Disable" button and observe the behavior.

[Expected result]:
- The "Doorhanger Nudges" experiment is uninstalled and no longer displayed on the page.

[Actual result]:
- The "Doorhanger Nudges" is disabled.

[Additional Notes]:
- The addon's name is displayed as "Showing a search doorhanger when the urlbar is focused study." as bug #11 is encountered.
- I have attached a screenshot of the issue:
![disabled](https://user-images.githubusercontent.com/40393891/43908019-8f3da4a4-9bff-11e8-83ed-b2f7d9305623.png)

**Comment by Standard8** [comment]
Isn't this the expected behaviour when someone clicks disable on an extension? Or are Shield add-ons treated differently?

If this is a shield difference, then we need to work out if this is automatically handled when the add-on is installed via shield itself rather than manually.

**Comment by Softvision-PatriciuPop** [comment]
We've encountered this behavior on other shield studies ( eg. [Breach Alerts](https://github.com/mozilla/blurts-addon/issues/34), [DNS over HTTPS](https://github.com/jonathanKingston/http-dns/issues/13)) and a guideline was created detailing how a shield study should behave in case of disabling/removing it. The expected behavior can be found [here](https://github.com/mozilla/shield-studies-addon-utils/issues/246).

**Comment by Softvision-PatriciuPop** [comment]
I have verified this issue using the latest Search Nudges version 1.5.1 and it's still reproducible if the user disables/removes the addon without restarting the browser after installation. It's also reproducible if the user disables/removes the addon after it expires. Tested on Windows 10 x64, Mac 10.13.6 and Arch Linux 4.12. 
Considering this, the issue should be reopened.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest "Search Nudges" version (1.7.0) and it is still reproducible. In the current version even after you restart the browser and click the "Disable" button, the "Doorhanger Nudges" remains installed and displayed on the page.

Considering this, I will reopen the issue.

**Comment by SoftVision-CosminMuntean** [comment]
I have created a custom build with the latest fixes from master, but unfortunately this issue is still reproducible. The add-on is not removed after the the "Disable" button is clicked. Even if you restart the browser 

However, it seems that issue #19 is fixed with this version.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest "Search Nudges" version (1.8.0) and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
