### ISSUE TITLE
"Exit" and "expired" pings are generated each time the browser is restarted after ending the study

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mikedeboer/shield-search-nudges#17]
[Affected versions]:
- Firefox 61.0.2 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
1. "extensions.legacy.enabled" set to true;
2. "extensions.shield-search-nudges.variation" string with the "doshow" value.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Open a new tab and click the "Okay, got it" button.
3. Restart the browser twice.
4. Navigate to "about:telemetry" page and observe how many "exit" and "expire" pings were generated.

[Expected result]:
- "Exit" and "expired" pings are generated only once.

[Actual result]:
- "Exit" and "expired" pings are generated twice.

[Notes]:
- "Exit" and "expired" pings are generated each time the browser is restarted.
- This is reproducible with all 3 ways of ending the study:
1. The user clicks on the "Okay, got it" button
2. The user clicks in the address bar whilst the doorhanger is displayed (please see #16 )
3. The doorhanger has been displayed a total of four times.
- This is reproducible with both "control" and "treatment" branches.
- Here is a screen recording with this issue:

![pings](https://user-images.githubusercontent.com/26000308/43911320-df6be460-9c07-11e8-81fc-ae91d31f6bf4.gif)

**Comment by Softvision-CristinaBadescu** [comment]
I've tested this issue and it is still reproducible using the latest version of "Search Nudges" add-on (1.5.1), on Windows 10 x64, Mac 10.13.6 and Arch Linux 4.12.
Considering this, the issue should be reopened (I don't have the right to do this, at the moment).

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest "Search Nudges" version (1.6.0) and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
