### ISSUE TITLE
The survey is not launched after the study expiration nor after user disable

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mikedeboer/shield-search-nudges#18]
[Notes]:
- This issue is reproducible on both "control" and "treatment" branches.
- The survey appearance cannot be tested when the study expires due to issue #14.
- According to the study's [PHD](https://docs.google.com/document/d/1-F8toIUWo99fl1iFsnTen262C-8N1TbEHPot6sqh9FA/edit), the users should be surveyed

[Affected versions]:
- Firefox Release 61.0.2
Firefox Beta 62.0b15

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Doorhanger Nudges version 1.4.0 addon is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons>Extensions" and click the "Door Hanger Nudges" add-on.
3. Click the "Remove" button and observe the behavior.

[Expected result]:
- The survey is launched in a new tab.

[Actual result]:
- The survey is not launched in a new tab.

[Aditional Notes]:
- Beside the user disable and expiration scenarios, the survey is also not launched when the following citerias are met:
1. The user clicks on the "Okay, got it" button
2. The user clicks in the address bar whilst the doorhanger is displayed
3. The doorhanger has been displayed a total of four times.

**Comment by Standard8** [comment]
I believe this is expected at the moment, Javaun said:

> There will be a survey, but we get that for free with Shield and it's based on the targeting of the Shield experiment ID

So I assume that means that Normandy will automatically trigger the survey, but I'm not 100% sure.

**Comment by mikedeboer** [comment]
@gregglind Are you aware of how this works? We didn't specify a specific survey, and I don't know if a default one will be launched if that's the case. I'd also be fine when the answer is 'no study will be launched', but at the moment I don't know.

**Comment by mikedeboer** [comment]
(We're using your old-style template)
