### ISSUE TITLE
The "Undo" option is wrongly displayed after the addon is removed

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mikedeboer/shield-search-nudges#19]
[Affected versions]:
- Firefox release Version 61.0.2
- Nightly Version 63.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.shield-search-nudges.variation" boolean pref is set to "doshow".
- Doorhanger Nudges version 1.4.0 addon is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons>Extensions" and click the "Remove" button of the "Showing a search doorhanger when the urlbar is focused study." add-on.
3. Observe the behavior.

[Expected result]:
- The "Showing a search doorhanger when the urlbar is focused study." experiment is uninstalled and no longer displayed on the page.

[Actual result]:
- The "Undo" option is displayed.

[Additional Notes]:
- I have attached a screen recording of the issue:
![undo](https://user-images.githubusercontent.com/40393891/43949112-41d8079a-9c95-11e8-9eeb-a5769fe52428.gif)

**Comment by Standard8** [comment]
Is this different from other shield studies installed via this method?

This is standard add-on manager functionality, so I'd expect it to do this.

**Comment by Standard8** [comment]
Unless we're missing some special sort of shield flag...

**Comment by Softvision-PatriciuPop** [comment]
We've encountered this behavior on other shield studies ( eg. [Breach Alerts](https://github.com/mozilla/blurts-addon/issues/34), [DNS over HTTPS](https://github.com/jonathanKingston/http-dns/issues/13)) and a guideline was created detailing how a shield study should behave in case of disabling/removing it. The expected behavior can be found [here](https://github.com/mozilla/shield-studies-addon-utils/issues/246).

**Comment by Softvision-PatriciuPop** [comment]
I have verified this issue using the latest Search Nudges version 1.5.1 and it's still reproducible if the user disables/removes the addon without restarting the browser after installation. It's also reproducible if the user disables/removes the addon after it expires. Tested on Windows 10 x64, Mac 10.13.6 and Arch Linux 4.12. 
Considering this, the issue should be reopened.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest "Search Nudges" version (1.7.0) and the issue is still reproducible if the user removes the addon without restarting the browser after installation.
However, after the browser is restarted and you click the "Remove"  button the experiment is uninstalled and no longer displayed on the page.

Considering this I will reopen this issue.

**Comment by mikedeboer** [comment]
@SoftVision-CosminMuntean I assume you didn't restart the browser before you disabled or removed the addon?

**Comment by SoftVision-CosminMuntean** [comment]
Yes, I didn't restart the browser. If I restart the browser and c lick the "Remove" button, the experiment is successfully removed.

**Comment by mikedeboer** [comment]
Alright, that makes this one and #15 easy to fix. Thanks.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using a created build from master with the latest changes,  and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
