### ISSUE TITLE
here was an error during installation: Add-on search-nudges@shield.mozilla.org is not compatible with application version. add-on minVersion: 57.0. add-on maxVersion: *.

### ISSUE THREAD

**Issue by pdehaan** [mikedeboer/shield-search-nudges#2]
```sh
➜  shield-search-nudges git:(feature-wip) $ git rev-parse --short HEAD # 8235a07
```

If I run <kbd>$ FIREFOX_BINARY=beta node run-firefox.js</kbd> in iTerm in macOS, I get the following error in _about:debugging_:

> There was an error during installation: Add-on search-nudges@shield.mozilla.org is not compatible with application version. add-on minVersion: 57.0. add-on maxVersion: *.

And my browser console says that the add-on was disabled.

> 1533082572492	addons.xpi-utils	WARN	disabling legacy extension search-nudges@shield.mozilla.org

https://github.com/mikedeboer/shield-search-nudges/blob/36e1f2bda74d6baa21d85de51c0d679aac4dbc85/package.json#L10-L11

I'm currently using the latest Firefox Beta v62.0b13, which is higher than the minVersion of "57" and should be within the maxVersion range of "*".

![browser_console_dos](https://user-images.githubusercontent.com/557895/43494197-6b15bac8-94e6-11e8-8c0c-3d0179b8c5f9.png)

**Comment by mikedeboer** [comment]
I can't reproduce this problem, so I'm assuming this has something to do with the setup you're using?
