### ISSUE TITLE
The add-on's description from "about:addons" page is not translated in localized builds

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mikedeboer/shield-search-nudges#22]
[Affected versions]:
- Firefox 61.0.2 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have Firefox Release 61.0.2 es-ES locale with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- Have the following preferences in the "about:config" page:
"extensions.legacy.enabled" set to true;
create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to the "about:addons" page -> Extensions tab.
3. Observe the add-on's description.

[Expected result]:
- The description is displayed in Spanish.

[Actual result]:
- The description is displayed in English.

[Notes]:
- This issue is also reproducible with other localized builds, such as:  de, ru, zh-CN and ar.
- Here is a screen recording with this issue:
![nudges - description translate](https://user-images.githubusercontent.com/31244235/43958557-7e52e392-9cb4-11e8-94cd-f77fc310a0ca.gif)

**Comment by Standard8** [comment]
@Softvision-CristinaBadescu Do you know if it is normal for most shield studies to have this localised?

**Comment by Softvision-CristinaBadescu** [comment]
@Standard8 We've encountered this behavior for other shield studies, such as DNS over HTTPS (https://github.com/jonathanKingston/http-dns/issues/1). If I correctly recall, you mentioned in an e-mail that it would be enough to test the most used locales and that the only difference should be the strings displayed.

**Comment by Standard8** [comment]
Thanks, we'll have to figure out if we want that part localised, and if so where to get the localisations from.

**Comment by mikedeboer** [comment]
WONTFIX - we're OK with not having this localized during the duration of this study.
