### ISSUE TITLE
The "general-shown" event is wrongly sent twice if the "General Onboarding" tip is displayed and a new tab is opened by using the "+" button

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mikedeboer/shield-search-nudges#27]
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the " Search Nudges" add-on (1.5.1) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- Have the following preference in the "about:config" page:
	- create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new tab and click the "Open a new tab" button.
3. Navigate to the "about:telemetry" page.
4. Observe how many "general-shown" events were generated.

**[Expected result]:**
- one "general-shown" event is displayed.

**[Actual result]:**
- two "general-shown" events are displayed.

**[Notes]:**
- This issue is not reproducible if you open the second tab by using the keyboard (Ctrl/Cmd + T keys combination).
- This issue is not reproducible on Linux OSes.
- Here is a screen recording of the issue:
![nudges - general shown](https://user-images.githubusercontent.com/31244235/44214656-5b51c380-a179-11e8-8333-1ab677734f8c.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest "Search Nudges" version (1.6.0) and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
