### ISSUE TITLE
Both "general-hidden" and "general-hidden-buttonclick" events are sent after the "Okay, got it" button was clicked

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mikedeboer/shield-search-nudges#30]
*[Affected versions]:*
- Firefox 61.0.2 and above

*[Affected Platforms]:*
- All Windows
- All Mac
- All Linux

*[Prerequisites]:*
- Have a new Firefox profile with the latest version of the "Search Nudges" add-on (1.6.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- Have the following preferences in the "about:config" page:
	- "xpinstall.signatures.required" set to false;
	- "extensions.legacy.enabled" set to true;
	- create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

*[Steps to reproduce]:*
1. Open the browser with the profile from prerequisites.
2. Open a new tab and click the "Okay, got it" button.
3. Navigate to "about:telemetry" page and observe the last sent events.

*[Expected result]:*
- The "general-shown" and "general-hidden-buttonclick" events are sent.

*[Actual result]:*
- The "general-shown", "general-hidden" and "general-hidden-buttonclick" events are sent.

*[Notes]:*
- The issue is also reproducible for the "Redirect" tip.
- Based on the [Telemetry.md](https://github.com/mikedeboer/shield-search-nudges/blob/master/docs/TELEMETRY.md) doc, the "<target>-hidden" is sent only when the user closed the prompt by clicking somewhere else.
- Attached a screen recording of the issue:
![hidden event](https://user-images.githubusercontent.com/19226534/44277537-b7891600-a253-11e8-91f6-6cf778172469.gif)

**Comment by mikedeboer** [comment]
I *think* `onLocationChange` is fired too often and ends up attempting to show the tip twice in rapid succession.
Should be easy to debug & fix.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest "Search Nudges" version (1.6.0) and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
