### ISSUE TITLE
The add-on is not removed after the study expires

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mikedeboer/shield-search-nudges#31]
**[Affected versions]:**
- 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Create the "extensions.shield-search-nudges.variation" string with the "doshow" value.
- Have a new Firefox profile with the latest version of the "Search Nudges" add-on (1.8.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new tab and click the "Okay, got it" button from the doorhanger.
3. Open a new tab and navigate to "about:addons.
4. Observe the extension section.

**[Expected result]:**
- The "User search study" add-on is removed.

**[Actual result]:**
- The "User search study" add-on is still displayed.

**[Notes]:**
- This issue is also reproducible if you the AwesomeBar was clicked whilst one of the tips was shown or the tips were shown more than four times in sum.
- This issue is reproducible on both control and treatment branches.
- If you exit the study by triggering both "General" and "Redirect" doorhangers in the same session the "exit" and "expired" pings are displayed only after a browser restart.
- Attached a screen recording of the issue:
![rec of the issue - add-on does not expire](https://user-images.githubusercontent.com/37875464/44460949-bcfdac00-a617-11e8-8441-72c82d867629.gif)

**Comment by mikedeboer** [comment]
Ah yes, a regression. I forgot to update a bit of code between versions 1.7.0 and 1.8.0 :(

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue using latest "Search Nudges" version (1.8.1) and it's no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux 4.12.

But, if you exit the study by triggering both "General" and "Redirect" doorhangers in the same session the "exit" and "expired" pings and the survey page are displayed only after a browser restart. However, if the study expires by ignoring the tips more than four times in sum, clicking the AwesomeBar whilst one of the tips was shown or clicking the "Okay, got it" button the "exit" and "expired" pings and the survey are triggered when a new tab is opened in the same session.

We don't consider this an issue, but @mikedeboer  can you please give us your opinion regarding this? Should the behavior be changed in order to be the same for all expiration criteria?

**Comment by mikedeboer** [comment]
I have discussed this with Cosmin as well on Slack and mentioned that it's not considered a problem by us. We're fine to ship the addon with the current behavior. Thanks!
