### ISSUE TITLE
The doorhanger wrongly remains displayed after starting typing in the "Address Bar"

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mikedeboer/shield-search-nudges#7]
**[Affected versions]:**
- Firefox 61.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
	- "extensions.legacy.enabled" set to true;
	- create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new tab and start typing in the "Address bar" after the doorhanger is displayed.
3. Observe the behavior.

**[Expected result]:**
- The "Nudges" doorhanger is dismissed.

**[Actual result]:**
- Windows and Linux: The "Nudges" doorhanger remains displayed behind the search suggestions.

- Mac: The "Nudges" doorhanger remains displayed over the search suggestions.

**[Notes]:**
- The "Nudges" doorhanger remains displayed even after the search was made and the results page is displayed.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/43838671-b33da79a-9b24-11e8-9516-d26831cef378.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest "Search Nudges" version (1.6.0) and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
