### ISSUE TITLE
The doorhanger's "Okay, got it" button cannot be focused using the "Tab" key

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mikedeboer/shield-search-nudges#9]
**[Affected versions]:**
- Firefox 61.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
	- "extensions.legacy.enabled" set to true;
	- create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new tab and press the "Tab" key multiple times.
3. Observe the behavior.

**[Expected result]:**
- The doorhanger's button is focused.

**[Actual result]:**
- The doorhanger's button cannot be focused regardless of how many times the "Tab" key is pressed.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/43844555-b4a38bf0-9b32-11e8-8f08-ba8907b94ee4.gif)

**Comment by mikedeboer** [comment]
This is indeed a serious accessibility issue, but more something we'll need to fix when the study is potentially integrated into Firefox. WONTFIX for now.
